### ISSUE TITLE
Extension conflicts with a different extension

### ISSUE THREAD

**Issue by rafistrauss** [coderfin/logical-properties#2]
Hi again - looks like your fix for #1 works quite nicely with one caveat; it seems that this extension no longer plays nicely with a different extension I have installed ([Todo Tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree&ssr=false#overview)).

Error output:

```log
[2022-01-06 11:58:51.874] [exthost] [error] Activating extension coderfin.logical-properties failed due to an error:
[2022-01-06 11:58:51.874] [exthost] [error] SyntaxError: Invalid flags: dgi
	at _ (/Users/RaphaelStrauss/.vscode/extensions/gruntfuggly.todo-tree-0.0.214/dist/extension.js:114:74341)
	at Array.l (/Users/RaphaelStrauss/.vscode/extensions/gruntfuggly.todo-tree-0.0.214/dist/extension.js:114:3580)
	at Object.parse (/Users/RaphaelStrauss/.vscode/extensions/gruntfuggly.todo-tree-0.0.214/dist/extension.js:114:71938)
	at Object.a.parse (/Users/RaphaelStrauss/.vscode/extensions/gruntfuggly.todo-tree-0.0.214/dist/extension.js:1:12591)
	at Object.parse (/Users/RaphaelStrauss/.vscode/extensions/gruntfuggly.todo-tree-0.0.214/dist/extension.js:114:415)
	at i (/Users/RaphaelStrauss/.vscode/extensions/gruntfuggly.todo-tree-0.0.214/dist/extension.js:52:165)
	at Array.get [as indices] (/Users/RaphaelStrauss/.vscode/extensions/gruntfuggly.todo-tree-0.0.214/dist/extension.js:52:2895)
	at getDiagnostics (/Users/RaphaelStrauss/.vscode/extensions/coderfin.logical-properties-0.1.10/extension.js:247:21)
	at handler (/Users/RaphaelStrauss/.vscode/extensions/coderfin.logical-properties-0.1.10/extension.js:290:48)
	at activate (/Users/RaphaelStrauss/.vscode/extensions/coderfin.logical-properties-0.1.10/extension.js:416:9)
	at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:100:15293)
	at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:100:14966)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:100:13144
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 0)
```

OS: Mac 10.15.2
Vscode version: `1.63.2`
Logical properties version: `v0.1.10`
Todo Tree version: `v0.0.214`

Thanks again for this cool tool!

**Comment by coderfin** [comment]
I have resolved this issue in version 0.1.11.
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/coderfin/vsextensions/logical-properties/0.1.11/vspackage

As always if you continue to experience problems feel free to reopen this issue or create a new issue.

Thanks again!
